Repository naturalcrit/Axe, pull requests merged in 2024-05, with the labels that each got.

#11 Update README.md
  README.md
Labels: documentation, 🔍 R0 - Needs first review 👀

#10 Basic styling settings
  README.md
  src/components/builderPage/builderPage.css
  src/components/builderPage/builderPage.jsx
  src/components/sheetSettings.jsx
  src/components/sheetSettings/sheetSettings.css
  src/components/sheetSettings/sheetSettings.jsx
Labels: 🔍 R0 - Needs first review 👀

#14 Homepage style and favicon
  public/favicon.ico
  public/index.html
  src/assets/fonts/CODE Bold.otf
  src/assets/fonts/CODE Light.otf
  src/assets/fonts/fonts.css
  src/assets/images/Axe_Builder.png
  src/assets/images/HB_homepage.png
  src/components/builderPage/builderPage.css
  src/components/builderPage/builderPage.jsx
  src/components/homePage/homePage.css
  src/components/homePage/homePage.jsx
  src/components/nav/nav.css
  src/components/nav/navBar.jsx
  src/components/sheetSettings/sheetSettings.jsx
  src/styles/main.css
  src/styles/reset.css
Labels: 🔍 R0 - Needs first review 👀

#21 add compactType=null to remove vertical packing
  src/components/builderPage/builderPage.css
  src/components/builderPage/builderPage.jsx
  src/components/draggables/draggables.css
  src/components/draggables/emptySace/emptySpace.css
  src/components/draggables/emptySace/emptySpace.jsx
  src/components/draggables/labelInput.jsx
  src/components/draggables/labelInput/labelInput.css
  src/components/draggables/labelInput/labelInput.jsx
  src/components/draggables/statInput/statInput.css
  src/components/draggables/statInput/statInput.jsx
  src/components/draggables/textArea/textarea.css
  src/components/draggables/textArea/textarea.jsx
  src/components/draggables/textarea.jsx
  src/components/nav/nav.css
  src/styles/main.css
Labels: 🔍 R3 - Reviewed - Awaiting Fixes

#25 Export as HTML, JSON, Import JSON, all but better
  src/components/builderPage/builderPage.css
  src/components/builderPage/builderPage.jsx
  src/components/builderPage/sheet.css
  src/components/draggables/draggables.css
  src/components/draggables/emptySace/emptySpace.css
  src/components/draggables/labelInput/labelInput.css
  src/components/draggables/statInput/statInput.css
  src/components/draggables/textArea/textarea.css
  src/components/sheetSettings/sheetSettings.css
  src/components/sheetSettings/sheetSettings.jsx
  src/styles/main.css
Labels: 🔍 R3 - Reviewed - Awaiting Fixes
